stages:
  - build
  
image: maven:3.6-jdk-8-slim

variables:
  GIT_SUBMODULE_STRATEGY: normal
  MAVEN_OPTS: "-Djava.awt.headless=true -Dmaven.repo.local=.m2/repository -DbuildTimestamp=${CI_COMMIT_TIMESTAMP} -DbuildNumber=${CI_PIPELINE_ID} -DbuildCommit=${CI_COMMIT_SHA} -DbuildUser=${GITLAB_USER_LOGIN}"  
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode --errors --fail-at-end --show-version flatten:flatten"
  
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - .m2/repository

# Build normal para ramas principales
build:maven:
  stage: build
  only: 
    - main
    - develop
    - branches
  script:
    - mvn $MAVEN_CLI_OPTS deploy -DskipTests -Dgenerate-pos-lib
  artifacts:
    paths:
      - pos-gui/target/lib
    expire_in: 1 hour

# Build cuando se crea un tag
build:tag:
  stage: build
  only:
    - tags
  script:
    - echo "Compilando versión ${CI_COMMIT_TAG}"
    - mvn $MAVEN_CLI_OPTS deploy -DskipTests -Drevision=${CI_COMMIT_TAG} -Dgenerate-pos-lib
  artifacts:
    paths:
      - pos-gui/target/lib
    expire_in: 1 hour